name: FTL (Win64)

on:
  push:
    branches: [ "main", "stable" ]
  pull_request:
    branches: [ "main", "stable" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Setup project
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/setup.sh

      - name: Compile FTL
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/ftl.sh

      - name: 'Download and compile external lib: Funchook'
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/funchook.sh

      - name: 'Download external lib: Doorstop'
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/doorstop.sh

      - name: 'Download external lib: CoreCLR'
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/coreclr.sh

      - name: Create package
        run: bash feraltweaks-bootstrap/scripts/build-crosscompile-win64/package.sh

      - name: Publish build artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'FeralTweaksLoader Latest (Win64)'
          path: feraltweaks-bootstrap/build/package
